### ISSUE TITLE
Como cambiar el color barra de progreso

### ISSUE THREAD

**Issue by ccruzh** [davidherney/tepuy#10]
He buscado dentro de styles.css, pero no logro cambiar el color de progreso de la barra, ni darle un poco de curvatura:

`<div  class="measuring-progress"></div>`

Agradezco tu ayuda :)

![progreso](https://user-images.githubusercontent.com/53269196/63270085-11545f80-c25d-11e9-8437-86a9a11cce1e.png)

**Comment by davidherney** [comment]
Hola @ccruzh 

revisa la documentación de la plantilla que está en la misma plantilla. En la página "Maquetación" hay una descripción de las posibilidades de la barra de progreso. La que estás usando es la del sistema y por ende toma los colores del sistema, pero se puede usar varias en HTML, según se indica en la opción: "Indicador de progreso"

Saludos

**Comment by ccruzh** [comment]
Gracias @davidherney, como siempre muy oportuna tu ayuda :)
