### ISSUE TITLE
Problema con <span class="notmobile">

### ISSUE THREAD

**Issue by ccruzh** [davidherney/tepuy#12]
Hola, estoy tratando de crear dos menús diferentes:  Uno para computadores escritorio y otro para moviles.

El tag `<span class="onlymobile">` me funciona correctamente mostrando la info solo en móviles, pero el tag `<span class="notmobile">` me esta vizualizando en computadores escritorio y en móviles.

A que puede deberse el problema?

**Comment by davidherney** [comment]
Hola @ccruzh ...

Debes tener en cuenta que los menú se manejan diferentes a otros elementos ya que se procesan para ajustar la navegación. Incluso la vista de un menú en móvil siempre se procesa para que quede en el menú flotante lateral. Si lo que deseas es tener algo más personalizado, podrías construirlo con elementos HTML simples, sin usar los menús y simplemente apuntando a las páginas en cuestión, de esa manera te debería de funcionar y no se procesaría a como son los menús por defecto.
Además, no tienes que meter los elementos en un span con la clase en cuestión, puedes ponerla directamente sobre el elemento que quieres controlar.

Saludos

**Comment by ccruzh** [comment]
Muchas gracias por tu respuesta, te voy a contar porque estoy tratando de utilizar un doble menú (dependiendo si es de escritorio o móvil).  Tengo un menú en la parte inferior que deseo que se mantenga visible en modo móviles, pero cuando esta en modo escritorio uso el atributo `title` para dar una descripción del botón, pero en el modo móvil no sale y quiero poder colocar un texto a el botón en modo móvil que me diga para que es el botón (creo el botón con el texto dentro de la misma imagen).

Te agradezco si me puedes formular una posible solución ;)
