### ISSUE TITLE
Como parar video incrustado iframe

### ISSUE THREAD

**Issue by ccruzh** [davidherney/tepuy#13]
Hola, he creado un iframe responsive desde el cual llamo un html que carga un video, al darle reproducir y cambiar de página, se sigue reproduciendo, hay alguna forma de pararlo?

**Comment by davidherney** [comment]
Hola...

Desde la plantilla solamente se controla el video que se carga directamente en el contenido ¿por qué no lo cargas directamente? ¿por qué desde un iframe?

Saludos

**Comment by ccruzh** [comment]
Porque el video es parte de una interactividad que tiene varias partes :(

**Comment by ccruzh** [comment]
Puedo colocar un script que se ejecute cada vez que paso a la siguiente o a la anterior página?

**Comment by davidherney** [comment]
Pero tendrías que modificar el lib.js y el mobilelib.js, para esa acción se tienen los disparadores:
dhbgApp.actions.beforeChangePage
dhbgApp.actions.afterChangePage

**Comment by ccruzh** [comment]
Ya lo hice pero agregando un evento onclick en los botones.

**Comment by ccruzh** [comment]
Ya lo implementé en lib y mobilelib, adicionando una función en dhbgApp.loadFullPage
