### ISSUE TITLE
Como desactivar pantallas en navegación secuencial 

### ISSUE THREAD

**Issue by ccruzh** [davidherney/tepuy#14]
Hay algunas pantallas como glosario,  bibliografía, etc..., que deseo no las tenga en cuenta la navegación secuencial y que solo se pueda acceder a ellas por links directos desde íconos, es esto posible?

**Comment by davidherney** [comment]
Si las dejas como páginas no es posible, te recomiendo que en esos casos las coloques como ventanas modales con w-content.
Saludos

**Comment by ccruzh** [comment]
Ok, muchas gracias por la orientación.
