### ISSUE TITLE
Problema Arrastrar y soltar - modo completar 

### ISSUE THREAD

**Issue by ccruzh** [davidherney/tepuy#15]
Hola, estoy Implementando este tipo de actividad, pero al finalizarla no me indica cuáles tuve bien y cuáles tuve mal, donde puede estar la falla?

**Comment by davidherney** [comment]
Hola...

Asegúrate que estés agregando el "box_end" en un contenedor para la respuesta. Algo como:
<div class="box_end"></div>

Y revisa que no sobre-escribas los colores que se asignan en las respuestas correctas/incorrectas o asigna tus propios estilos.

Saludos

**Comment by ccruzh** [comment]
Muchas gracias ya lo puse solucionar.
