### ISSUE TITLE
Como generar hipervinculos a secciones

### ISSUE THREAD

**Issue by ccruzh** [davidherney/tepuy#7]
Hola, primero que todo felicitaciones por su trabajo.  deseo crear un mapa de navegación donde aparezcan las secciones creadas, así como las muestra el menú. mi pregunta es como creo un hipervinculo a una sección?

**Comment by davidherney** [comment]
Hola @ccruzh, en el contenido de la misma plantilla se describen esos asuntos. Ese específicamente, si te entiendo bien, está en la primera página donde se menciona el atributo "data-section" que sirve precisamente para apuntar a una sección específica dentro de una página.

Espero te sirva.

Saludos

**Comment by ccruzh** [comment]
Muchas gracias, no lo había visto ;)
